apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/aia9313335/monitoring.git
    targetRevision: HEAD
    path: .
    helm:
      parameters:
        - name: namespace
          value: monitoring
  destination: 
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true